package org.onekash.kashcal.widget

import android.content.Context
import androidx.glance.color.ColorProviders
import androidx.glance.color.colorProviders
import androidx.glance.material3.ColorProviders
import kotlinx.coroutines.flow.first
import org.onekash.kashcal.data.preferences.KashCalDataStore
import org.onekash.kashcal.ui.theme.ColorSource
import org.onekash.kashcal.ui.theme.WIDGET_ACCENT_CONTRAST_LEVEL
import org.onekash.kashcal.ui.theme.accentColorScheme

/**
 * Builds Glance [ColorProviders] from an accent seed, so widgets recolor with the same accent
 * the app uses. Light and dark are generated by the shared [accentColorScheme] (pure HCT, no
 * Context/composition), then handed to Glance's Material 3 interop, which picks light vs dark
 * against the system day/night setting at render time.
 *
 * Widgets build the scheme at [WIDGET_ACCENT_CONTRAST_LEVEL] (a small positive axis): the header
 * rides the muted `secondaryContainer` role. Its text (`onSecondaryContainer`) is a
 * guaranteed-contrast M3 pair with it, so it clears AA for any seed by construction — including the
 * wallpaper-derived automatic accent; the low axis lifts it to a comfortable ~5:1 across the tested
 * palette while holding the header at nearly the body's tone, so the two read as one near-uniform
 * tinted panel rather than a header band over a plainer body.
 *
 * Widgets also opt out of the achromatic-container snap (`snapAchromaticContainers = false`). The
 * header rides `secondaryContainer`; snapping that role to pure white/black for the white/black
 * seeds would blow the header out to the extreme instead of the muted accent tone. At this low
 * contrast level the raw engine already gives the achromatic header 5:1+ text, so the snap is
 * unnecessary here.
 *
 * Finally, the body (`widgetBackground`) is pinned to `surfaceVariant` — the most-tinted body role
 * that keeps item text at full contrast for every seed. `secondaryContainer` carries more chroma,
 * but its non-guaranteed pairing with `onSurface`/`onSurfaceVariant` drops below WCAG AA for
 * saturated and wallpaper-derived seeds (measured item text as low as ~2.5:1), so it is not a safe
 * body. `surfaceVariant` still shows a visible accent tint (chroma up to ~0.15 for chromatic seeds)
 * while keeping item text at ~7:1+ (onSurface) and secondary text at ~5.5:1+ (onSurfaceVariant) for
 * every seed handed here — both the in-app accent (SEED) and the wallpaper-derived system accent
 * used for the automatic source.
 */
fun accentColorProviders(seed: Int): ColorProviders {
    val light = accentColorScheme(
        seed, dark = false,
        contrastLevel = WIDGET_ACCENT_CONTRAST_LEVEL,
        snapAchromaticContainers = false,
    )
    val dark = accentColorScheme(
        seed, dark = true,
        contrastLevel = WIDGET_ACCENT_CONTRAST_LEVEL,
        snapAchromaticContainers = false,
    )
    // Base carries every role wired from the two schemes via Glance's Material 3 interop; we then
    // republish it through the core DSL overriding ONLY widgetBackground -> surfaceVariant. Reading roles
    // back off `base` keeps all other roles in lockstep with the interop (no 26-way manual mirror).
    val base = ColorProviders(light = light, dark = dark)
    return colorProviders(
        primary = base.primary,
        onPrimary = base.onPrimary,
        primaryContainer = base.primaryContainer,
        onPrimaryContainer = base.onPrimaryContainer,
        secondary = base.secondary,
        onSecondary = base.onSecondary,
        secondaryContainer = base.secondaryContainer,
        onSecondaryContainer = base.onSecondaryContainer,
        tertiary = base.tertiary,
        onTertiary = base.onTertiary,
        tertiaryContainer = base.tertiaryContainer,
        onTertiaryContainer = base.onTertiaryContainer,
        error = base.error,
        errorContainer = base.errorContainer,
        onError = base.onError,
        onErrorContainer = base.onErrorContainer,
        background = base.background,
        onBackground = base.onBackground,
        surface = base.surface,
        onSurface = base.onSurface,
        surfaceVariant = base.surfaceVariant,
        onSurfaceVariant = base.onSurfaceVariant,
        outline = base.outline,
        inverseOnSurface = base.inverseOnSurface,
        inverseSurface = base.inverseSurface,
        inversePrimary = base.inversePrimary,
        widgetBackground = base.surfaceVariant,
    )
}

/**
 * Resolves the [ColorProviders] a widget should use. Mirrors the app's color-source resolution
 * (including the retired-teal migration) so app and widgets stay in sync.
 *
 * Both sources build tinted providers via [accentColorProviders] from a seed, so the widget body
 * carries the same visible accent tint on either — the SEED source from the user's picked accent,
 * the automatic (Material You) source from the wallpaper-derived system accent ([dynamicAccentSeed]).
 * Handing the automatic source a bare `GlanceTheme { }` (the previous behavior) let the platform
 * pick its muted surface/widgetBackground roles, so the body read flat while the header still showed
 * accent. Seeding it from the same system accent the launcher uses gives the automatic body the
 * same tint treatment — including the [accentColorProviders] `widgetBackground -> surfaceVariant` override
 * that keeps item text at full contrast.
 *
 * Returns null only when the system accent can't be resolved (below API 31, or an OEM that doesn't
 * populate the system_accent palette); callers pass null through to a bare `GlanceTheme { }` so the
 * widget falls back to the platform dynamic colors rather than an untinted guess.
 */
suspend fun resolveWidgetAccentColors(
    context: Context,
    dataStore: KashCalDataStore,
): ColorProviders? {
    val source = ColorSource.fromPrefValue(
        explicit = dataStore.colorSource.first(),
        legacyTheme = dataStore.theme.first(),
    )
    val seed = if (source == ColorSource.SEED) {
        dataStore.accentSeed.first()
    } else {
        dynamicAccentSeed(context) ?: return null
    }
    return accentColorProviders(seed)
}

/**
 * The wallpaper-derived system accent as a packed ARGB seed, or null when it can't be read.
 *
 * `system_accent1_500` is the mid-tone of the primary Material You palette the launcher and system
 * UI theme from — the same source the app's dynamic face uses — so seeding the widget from it keeps
 * widgets in step with the automatic accent. Available API 31+ (the app's minSdk); guarded and
 * null-on-failure so a stripped OEM palette degrades to the platform colors instead of crashing.
 */
private fun dynamicAccentSeed(context: Context): Int? = runCatching {
    context.getColor(android.R.color.system_accent1_500)
}.getOrNull()
