package org.onekash.kashcal.widget

import androidx.glance.color.ColorProviders
import androidx.glance.color.colorProviders
import androidx.glance.material3.ColorProviders
import kotlinx.coroutines.flow.first
import org.onekash.kashcal.data.preferences.KashCalDataStore
import org.onekash.kashcal.ui.theme.ColorSource
import org.onekash.kashcal.ui.theme.WIDGET_ACCENT_CONTRAST_LEVEL
import org.onekash.kashcal.ui.theme.accentColorScheme

/**
 * Builds Glance [ColorProviders] from an accent seed, so widgets recolor with the same accent
 * the app uses. Light and dark are generated by the shared [accentColorScheme] (pure HCT, no
 * Context/composition), then handed to Glance's Material 3 interop, which picks light vs dark
 * against the system day/night setting at render time.
 *
 * Widgets build the scheme at [WIDGET_ACCENT_CONTRAST_LEVEL] (a small positive axis): the header
 * rides the muted `secondaryContainer` role. Its text (`onSecondaryContainer`) is a
 * guaranteed-contrast M3 pair with it, so it clears AA for any seed by construction — including the
 * wallpaper-derived automatic accent; the low axis lifts it to a comfortable ~5:1 across the tested
 * palette while holding the header at nearly the body's tone, so the two read as one near-uniform
 * tinted panel rather than a header band over a plainer body.
 *
 * Widgets also opt out of the achromatic-container snap (`snapAchromaticContainers = false`). The
 * header rides `secondaryContainer`; snapping that role to pure white/black for the white/black
 * seeds would blow the header out to the extreme instead of the muted accent tone. At this low
 * contrast level the raw engine already gives the achromatic header 5:1+ text, so the snap is
 * unnecessary here.
 *
 * Finally, the body (`widgetBackground`) is pinned to `surfaceVariant` — the most-tinted body role
 * that keeps item text at full contrast for every seed. `secondaryContainer` carries more chroma,
 * but its non-guaranteed pairing with `onSurface`/`onSurfaceVariant` drops below WCAG AA for
 * saturated seeds (measured item text as low as ~2.5:1), so it is not a safe body. `surfaceVariant`
 * still shows a visible accent tint (chroma up to ~0.15 for chromatic seeds) while keeping item text
 * at ~7:1+ (onSurface) and secondary text at ~5.5:1+ (onSurfaceVariant).
 *
 * This is only reached for the in-app SEED accent. The automatic (Material You) source does NOT come
 * through here — it renders on the device's genuine dynamic palette (see [resolveWidgetAccentColors]).
 */
fun accentColorProviders(seed: Int): ColorProviders {
    val light = accentColorScheme(
        seed, dark = false,
        contrastLevel = WIDGET_ACCENT_CONTRAST_LEVEL,
        snapAchromaticContainers = false,
    )
    val dark = accentColorScheme(
        seed, dark = true,
        contrastLevel = WIDGET_ACCENT_CONTRAST_LEVEL,
        snapAchromaticContainers = false,
    )
    // Base carries every role wired from the two schemes via Glance's Material 3 interop; we then
    // republish it through the core DSL overriding ONLY widgetBackground -> surfaceVariant. Reading roles
    // back off `base` keeps all other roles in lockstep with the interop (no 26-way manual mirror).
    val base = ColorProviders(light = light, dark = dark)
    return colorProviders(
        primary = base.primary,
        onPrimary = base.onPrimary,
        primaryContainer = base.primaryContainer,
        onPrimaryContainer = base.onPrimaryContainer,
        secondary = base.secondary,
        onSecondary = base.onSecondary,
        secondaryContainer = base.secondaryContainer,
        onSecondaryContainer = base.onSecondaryContainer,
        tertiary = base.tertiary,
        onTertiary = base.onTertiary,
        tertiaryContainer = base.tertiaryContainer,
        onTertiaryContainer = base.onTertiaryContainer,
        error = base.error,
        errorContainer = base.errorContainer,
        onError = base.onError,
        onErrorContainer = base.onErrorContainer,
        background = base.background,
        onBackground = base.onBackground,
        surface = base.surface,
        onSurface = base.onSurface,
        surfaceVariant = base.surfaceVariant,
        onSurfaceVariant = base.onSurfaceVariant,
        outline = base.outline,
        inverseOnSurface = base.inverseOnSurface,
        inverseSurface = base.inverseSurface,
        inversePrimary = base.inversePrimary,
        widgetBackground = base.surfaceVariant,
    )
}

/**
 * Resolves the [ColorProviders] a widget should use, or null to use the platform's genuine
 * Material You palette. Mirrors the app's color-source resolution (including the retired-teal
 * migration) so app and widgets stay in sync.
 *
 * - **SEED source** (in-app accent picker): builds tinted providers via [accentColorProviders] from
 *   the picked seed. There is no system palette to honor here, so the widget recolors to the user's
 *   chosen accent — the same scheme the app face derives from that seed.
 * - **Automatic / Material You source**: returns null so the widget renders on the device's genuine
 *   Material You palette (`GlanceTheme.colors` at the call site). We do NOT reseed a scheme from a
 *   single system-accent tone here: that overwrote the real dynamic palette (near-neutral system
 *   surfaces, accent where the system places it) with an app-derived tint, so the widget stopped
 *   matching the launcher and system UI. Automatic means "follow the system," so we defer to it.
 *
 * Callers pass null through to a bare `GlanceTheme { }` (`accentColors ?: GlanceTheme.colors`), which
 * is exactly the platform dynamic palette.
 */
suspend fun resolveWidgetAccentColors(
    dataStore: KashCalDataStore,
): ColorProviders? {
    val source = ColorSource.fromPrefValue(
        explicit = dataStore.colorSource.first(),
        legacyTheme = dataStore.theme.first(),
    )
    // Only the in-app SEED accent gets an app-derived scheme; the automatic source defers to the
    // device's genuine Material You palette via the null fallback at the call site.
    if (source != ColorSource.SEED) return null
    return accentColorProviders(dataStore.accentSeed.first())
}
